config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks, :only => [:new, :create]
  get 'feedbacks/success' => 'feedbacks#success', as: :success

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
 
    # fields validation for the database.
    validates :name, presence: true
    validates :email, presence: true, length: {in:5..255}
    validates :address, presence: true
    validates :message, presence: true
    validates :suggestion, presence: true
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
 
def new
    @feedback = Feedback.new
end
 
def create
    @feedback = Feedback.new(feedback_params)
    respond_to do |format|
        if @feedback.save
            format.html { redirect_to success_path, notice: 'Feedback was successfully submited.' }
        else
            format.html { render :new }
        end
    end
 end
 
 def success
 end
 
private
 
   def feedback_params
     params.require(:feedback).permit(:name, :email, :address, :message, :suggestion)
   end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/create.html.erb
<h1>Feedbacks#create</h1>
<p>Find me in app/views/feedbacks/create.html.erb</p>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>
 
 
<%= form_for(@feedback) do |f| %>
 <% if @feedback.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>
     <ul>
     <% @feedback.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 
 
 <div class="field">
   <%= f.label :name %><br>
   <%= f.text_field :name %>
 </div>
 
 <div class="field">
   <%= f.label :email %><br>
   <%= f.text_field :email %>
 </div>
 
 <div class="field">
   <%= f.label :address %><br>
   <%= f.text_field :address %>
 </div>
 
 <div class="field">
   <%= f.label :message %><br>
   <%= f.text_area :message %>
 </div>
 
 <div class="field">
   <%= f.label :suggestion %><br>
   <%= f.text_area :suggestion %>
 </div>
 
 <div class="actions">
   <%= f.submit %>
 </div>
 
<% end %>
 
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/success.html.erb
<h1 id="notice"><%= notice %></h1>
<br>
<%= link_to 'Submit New Feedback', new_feedback_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tableless</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>